services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_dev_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interbanking_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5433:5432"
    networks:
      - postgres_net

  postgres_test:
    image: postgres:15-alpine
    container_name: postgres_test_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interbanking_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres_net
    depends_on:
      - postgres

volumes:
  postgres_data:
  postgres_test_data: 

networks:
  postgres_net:  